### ISSUE TITLE
Bug in DurationModel training_score method

### ISSUE THREAD

**Issue by phipag** [phipag/PDS_Project#6]
Dear team,

when calling the training_score method after training the duration model I experience the following error:
```
Traceback (most recent call last):
  File "/Users/phipag/Git/pds/PDS_Project/venv/bin/nextbike", line 11, in <module>
    load_entry_point('PDS-Project', 'console_scripts', 'nextbike')()
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/phipag/Git/pds/PDS_Project/nextbike/cli/train/commands.py", line 23, in train
    duration_model.training_score()
  File "/Users/phipag/Git/pds/PDS_Project/nextbike/models/DurationModel.py", line 166, in training_score
    mae = mean_absolute_error(self.target.reshape(-1, 1), self.predictions)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 178, in mean_absolute_error
    y_true, y_pred, multioutput)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 86, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 578, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

This is the code I am using:
```python
duration_model = DurationModel()
duration_model.load_from_csv(filename)
duration_model.train()
duration_model.training_score()
```

**Comment by LHumpe** [comment]
Hey Philipp,

you need to call duration_model.predict() otherwise the model instance does not contain any predictions.

Let me know if that fixes your issue.

**Comment by phipag** [comment]
Thanks that worked.
